version: "3.8"

services:
  ctfd:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      UPLOAD_FOLDER: /var/uploads
      DATABASE_URL: "mysql+pymysql://ctfd:ctfd@db/ctfd"
      REDIS_URL: "redis://cache:6379"
      WORKERS: "1"
      LOG_FOLDER: /var/log/CTFd
      ACCESS_LOG: "-"
      ERROR_LOG: "-"
      REVERSE_PROXY: "true"
    volumes:
      - ctfd-logs:/var/log/CTFd
      - ctfd-uploads:/var/uploads
      - ./:/opt/CTFd:ro
    depends_on:
      - db
      - cache
    networks:
      - web
      - internal

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./conf/nginx/http.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - ctfd
    networks:
      - web

  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ctfd
      MARIADB_USER: ctfd
      MARIADB_PASSWORD: ctfd
      MARIADB_DATABASE: ctfd
      MARIADB_AUTO_UPGRADE: "1"
    volumes:
      - mysql-data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --wait_timeout=28800
      --log-warnings=0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - internal

  cache:
    image: redis:6
    restart: unless-stopped
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internal

volumes:
  ctfd-logs:
  ctfd-uploads:
  mysql-data:
  redis-data:

networks:
  web:
    driver: bridge
  internal:
    internal: true